# Generated by Django 2.2.6 on 2019-10-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='request',
            name='request',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
