# Generated by Django 2.2.6 on 2019-10-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20191013_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request',
            new_name='issue',
        ),
    ]
