# Generated by Django 2.2.6 on 2019-10-14 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20191014_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True, 'is_superuser': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
