# Generated by Django 2.2.6 on 2019-10-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_auto_20191014_1416'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='request',
            order_with_respect_to='is_closed',
        ),
    ]
