# Generated by Django 2.2.6 on 2019-10-14 19:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_auto_20191014_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
